In [295]:
import matplotlib.pyplot as plt
import requests as requests
import pandas as pd
import seaborn as sb
import numpy as np
import csv
from citipy import citipy

In [296]:
source = "./design_sources.csv"

In [297]:
source_df = pd.read_csv(source)
full_citation_df = source_df
source_df.head()

   citeID                                      full_citation
0     1.0  Chatterjee, S. and Hevner, A. (Eds.) (2006). P...
1     2.0  Archer, L. (1984). "Systematic method for desi...
2     3.0  Au, Y. (2001). "Design Science I: The Role of ...
3     4.0  Aydin, M. N., and Ozdenizci, B. (2013). "Desig...
4     5.0  Baskerville, R. (2008). "What Design Science i...

In [298]:
for col_name in source_df.columns: 
    print(col_name)

citeID
full_citation

In [299]:
source_df = source_df['full_citation'].str.split('(',1, expand=True)

In [300]:
source_df = source_df.rename(columns={0: 'authors', 1: 'year'})
source_df.head()

,authors,year
0,"Chatterjee, S. and Hevner, A.",Eds.) (2006). Proceedings of the 1st Conferenc...
1,"Archer, L.","1984). ""Systematic method for designers,"" in D..."
2,"Au, Y.","2001). ""Design Science I: The Role of Design S..."
3,"Aydin, M. N., and Ozdenizci, B.","2013). ""Design science perspective on NFC rese..."
4,"Baskerville, R.","2008). ""What Design Science is Not."" European ..."

In [301]:
###Create final df 
final_df = source_df
final_df = final_df.drop(['year'], axis=1 )
final_df.head()

                            authors
0    Chatterjee, S. and Hevner, A.
1                       Archer, L.
2                           Au, Y.
3  Aydin, M. N., and Ozdenizci, B.
4                  Baskerville, R.

In [302]:
full_citation_df.head()

   citeID                                      full_citation
0     1.0  Chatterjee, S. and Hevner, A. (Eds.) (2006). P...
1     2.0  Archer, L. (1984). "Systematic method for desi...
2     3.0  Au, Y. (2001). "Design Science I: The Role of ...
3     4.0  Aydin, M. N., and Ozdenizci, B. (2013). "Desig...
4     5.0  Baskerville, R. (2008). "What Design Science i...

In [303]:
#Combine authors and full_citation
del full_citation_df['citeID']
full_citation_df.head()

                                       full_citation
0  Chatterjee, S. and Hevner, A. (Eds.) (2006). P...
1  Archer, L. (1984). "Systematic method for desi...
2  Au, Y. (2001). "Design Science I: The Role of ...
3  Aydin, M. N., and Ozdenizci, B. (2013). "Desig...
4  Baskerville, R. (2008). "What Design Science i...

In [304]:
final_df = pd.concat([final_df, full_citation_df], axis=1)
final_df.head()

,authors,full_citation
0,"Chatterjee, S. and Hevner, A.","Chatterjee, S. and Hevner, A. (Eds.) (2006). P..."
1,"Archer, L.","Archer, L. (1984). ""Systematic method for desi..."
2,"Au, Y.","Au, Y. (2001). ""Design Science I: The Role of ..."
3,"Aydin, M. N., and Ozdenizci, B.","Aydin, M. N., and Ozdenizci, B. (2013). ""Desig..."
4,"Baskerville, R.","Baskerville, R. (2008). ""What Design Science i..."

In [305]:
source_df = source_df['year'].str.split(')',1, expand=True)
source_df = source_df.rename(columns={0: 'year', 1: 'rest'})

In [306]:
source_df.head()

   year                                               rest
0  Eds.   (2006). Proceedings of the 1st Conference on ...
1  1984  . "Systematic method for designers," in Develo...
2  2001  . "Design Science I: The Role of Design Scienc...
3  2013  . "Design science perspective on NFC research:...
4  2008  . "What Design Science is Not." European Journ...

In [307]:
##Drop year from new df 
year_df = source_df
year_df = year_df.drop(['rest'], axis=1 )
year_df.head()

   year
0  Eds.
1  1984
2  2001
3  2013
4  2008

In [308]:
##Combine year into final_df 
final_df = pd.concat([final_df, year_df], axis=1)
final_df.head()

,authors,full_citation,year
0,"Chatterjee, S. and Hevner, A.","Chatterjee, S. and Hevner, A. (Eds.) (2006). P...",Eds.
1,"Archer, L.","Archer, L. (1984). ""Systematic method for desi...",1984
2,"Au, Y.","Au, Y. (2001). ""Design Science I: The Role of ...",2001
3,"Aydin, M. N., and Ozdenizci, B.","Aydin, M. N., and Ozdenizci, B. (2013). ""Desig...",2013
4,"Baskerville, R.","Baskerville, R. (2008). ""What Design Science i...",2008

In [309]:
#Strip title from source_df 
del source_df['year']
source_df.head()

                                                rest
0   (2006). Proceedings of the 1st Conference on ...
1  . "Systematic method for designers," in Develo...
2  . "Design Science I: The Role of Design Scienc...
3  . "Design science perspective on NFC research:...
4  . "What Design Science is Not." European Journ...

In [310]:
#Remove period and quote from beginning of string 
source_df['rest'] = source_df['rest'].str.replace('.', '',1)
source_df['rest'] = source_df['rest'].str.replace('"', '',1)
source_df.head()

                                                rest
0   (2006) Proceedings of the 1st Conference on D...
1   Systematic method for designers," in Developm...
2   Design Science I: The Role of Design Science ...
3   Design science perspective on NFC research: R...
4   What Design Science is Not." European Journal...

In [311]:
#Split rest on second " from title 
source_df = source_df['rest'].str.split('"',1, expand=True)
source_df = source_df.rename(columns={0: 'title', 1: 'rest'})
source_df.head()

,title,rest
0,(2006) Proceedings of the 1st Conference on D...,None
1,"Systematic method for designers,","in Developments in Design Methodology, N. Cro..."
2,Design Science I: The Role of Design Science ...,Communication of the AIS 7(Article 1).
3,Design science perspective on NFC research: R...,None
4,What Design Science is Not.,European Journal of Information Systems 17(5)...

In [312]:
##Add title to final_df 
title_df = source_df
title_df = title_df.drop(['rest'], axis=1 )
final_df = pd.concat([final_df, title_df], axis=1)
final_df.head()

,authors,full_citation,year,title
0,"Chatterjee, S. and Hevner, A.","Chatterjee, S. and Hevner, A. (Eds.) (2006). P...",Eds.,(2006) Proceedings of the 1st Conference on D...
1,"Archer, L.","Archer, L. (1984). ""Systematic method for desi...",1984,"Systematic method for designers,"
2,"Au, Y.","Au, Y. (2001). ""Design Science I: The Role of ...",2001,Design Science I: The Role of Design Science ...
3,"Aydin, M. N., and Ozdenizci, B.","Aydin, M. N., and Ozdenizci, B. (2013). ""Desig...",2013,Design science perspective on NFC research: R...
4,"Baskerville, R.","Baskerville, R. (2008). ""What Design Science i...",2008,What Design Science is Not.